# -*- coding: utf-8 -*-
"""my_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MaO-HaoP8YBwm3rU502xw5f6QC_SIS5A
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np


df = pd.read_csv("coffee_shops_nyc.csv")#Load the data


#Basic cleaning#
df = df.drop_duplicates(subset="Name") #delete any duplicates of coffee shops with the same name

df["Rating"] = pd.to_numeric(df["Rating"], errors="coerce") #make sure the numerical categories have only numerical values
df["Review_Count"] = pd.to_numeric(df["Review_Count"], errors="coerce")

df = df.dropna(subset=["Rating", "Review_Count"])#delete rows without rating or review count

#Visualization#
plt.figure(figsize=(10, 4))

#graph 1 (bar chart): shows the amount of coffee shops that have a specific rating (0-5)
plt.subplot(1, 2, 1)
plt.hist(df["Rating"], bins=10)
plt.xlabel("Rating")
plt.ylabel("Number of coffee shops")
plt.title("Distribution of Ratings")

#graph 2 (scatter plot): shows the number of raviews that gave the same rating
plt.subplot(1, 2, 2)
plt.scatter(df["Review_Count"], df["Rating"], alpha=0.6)
plt.xlabel("Number of Reviews")
plt.ylabel("Rating")
plt.title("Number of Reviews per Rating")

plt.tight_layout()

top5 = df.sort_values("Rating", ascending=False).head(5)# Top 5 coffee shops with the highest rating

print("Top 5 coffee shops in NYC")
top5[["Name", "Rating", "Review_Count", "Price_Range"]]

"""##Dataset description
The dataset contains information about coffee shops in New York City, including name, rating, number of reviews, price range, and category.

##Exploratory analysis
A histogram of ratings shows that most shops score between 4.0 and 4.8.
A scatter plot of Rating vs. Review_Count illustrates how popularity relates to user scores.

##Top 5 results
I added a small table that shows the five highest-rated coffee shops that were extracted using a descending sort.

##Conclusion
Most NYC coffee shops receive strong ratings, and combining rating with review count provides a more accurate picture of overall popularity.
"""